// Intention (but de l'utilisateur) + résultat attendu, par parcours. Le runner (lib.mjs) y
// associe le RÉSULTAT FINAL mesuré (conforme / non conforme) et l'écrit dans rapport.json.
// C'est la documentation vivante du produit : chaque ligne = un contrat de comportement.
export const INTENTIONS = {
  // ── A. Service & recherche (public) ──
  'A01-accueil': { intention: "Un visiteur arrive sur Jurilux", attendu: "La page de recherche s'affiche" },
  'A02-parcours-guide': { intention: "Poser une question de droit", attendu: "Réponse sourcée + parcours guidé de questions de suivi" },
  'A03-clic-question-suivi': { intention: "Approfondir via une question de suivi proposée", attendu: "La question cliquée devient un nouveau tour" },
  'A04-autre-angle': { intention: "Explorer un autre angle de la question", attendu: "Un chip « Autre angle » est proposé" },
  'A05-mode-pedagogique': { intention: "Obtenir une réponse en mode pédagogique", attendu: "Réponse rendue avec parcours guidé" },
  'A06-filtres': { intention: "Restreindre la recherche via les filtres", attendu: "La réponse tient compte des filtres" },
  'A07-refus-hors-sujet': { intention: "Poser une question hors droit luxembourgeois", attendu: "Refus gracieux, aucune invention" },
  'A08-feedback-positif': { intention: "Signaler qu'une réponse est utile", attendu: "Le pouce positif est pris en compte" },
  'A09-feedback-manquant': { intention: "Signaler ce qui manquait à une réponse", attendu: "Un champ de précision s'ouvre puis s'envoie" },
  'A10-partager': { intention: "Partager une réponse par lien", attendu: "Un permalien est créé et copié" },
  'A11-permalien-public': { intention: "Ouvrir une réponse partagée (public)", attendu: "La page partagée s'affiche" },
  // ── B. Insight avocats (public) ──
  'B01-insight-recherche': { intention: "Rechercher un avocat", attendu: "La page Insight liste des avocats" },
  'B02-insight-analytics': { intention: "Consulter les analytics contentieux", attendu: "L'onglet analytics s'affiche" },
  // ── C. Auth & compte ──
  'C01-inscription': { intention: "Créer un compte", attendu: "Compte créé, plan étudiant actif" },
  'C02-connexion-pro': { intention: "Se connecter (compte pro)", attendu: "Session ouverte, plan pro affiché" },
  'C03-mauvais-mot-de-passe': { intention: "Se connecter avec un mauvais mot de passe", attendu: "Connexion refusée, formulaire maintenu" },
  'C04-deconnexion': { intention: "Se déconnecter", attendu: "Retour à l'état anonyme (se connecter)" },
  'C05-changer-mot-de-passe': { intention: "Ouvrir le volet Mon compte", attendu: "Section clés d'API visible" },
  'C06-quota-etudiant': { intention: "Dépasser le quota mensuel étudiant", attendu: "Refus gracieux « quota atteint »" },
  // ── D. Cabinet, rôles & cloisons ──
  'D01-cabinet-ouvrir': { intention: "Ouvrir son cabinet", attendu: "Le cabinet de l'utilisateur s'affiche" },
  'D02-cabinet-membres': { intention: "Voir les membres du cabinet", attendu: "Les membres sont listés" },
  'D03-cloison-owner-voit': { intention: "L'owner consulte un dossier restreint", attendu: "Le dossier restreint est visible" },
  'D04-cloison-collaborateur-404': { intention: "Un collaborateur non autorisé consulte le cabinet", attendu: "Le dossier restreint lui est INVISIBLE" },
  'D05-cloison-associe-autorise': { intention: "Un associé autorisé consulte le cabinet", attendu: "Le dossier restreint lui est visible" },
  'D06-isolation-inter-cabinet': { intention: "Un owner d'un autre cabinet regarde le sien", attendu: "Il ne voit pas les cabinets des autres" },
  // ── E. Veille ──
  'E01-alertes-liste': { intention: "Consulter ses alertes", attendu: "Les alertes existantes sont listées" },
  'E02-creer-alerte': { intention: "Créer une alerte de veille", attendu: "La nouvelle alerte apparaît" },
  // ── F. Vault ──
  'F01-vault-liste': { intention: "Consulter ses documents privés", attendu: "Les documents du Vault sont listés" },
  'F02-vault-upload': { intention: "Déposer un document au Vault", attendu: "Le document déposé apparaît" },
  'F03-vault-question-isolee': { intention: "Interroger ses seuls documents", attendu: "Une réponse isolée est produite" },
  'F04-vault-analyse-resume': { intention: "Résumer un document", attendu: "Un résumé s'affiche" },
  'F05-vault-isolation': { intention: "Un autre propriétaire consulte son Vault", attendu: "Il ne voit QUE ses documents" },
  // ── G. Compte pro / entreprise ──
  'G01-cles-api': { intention: "Consulter ses clés d'API", attendu: "La clé de service seedée est listée" },
  'G02-creer-cle-api': { intention: "Créer une clé d'API", attendu: "La nouvelle clé apparaît" },
  'G03-prompts': { intention: "Consulter sa bibliothèque de prompts", attendu: "Le prompt partagé est listé" },
  'G04-export-rgpd': { intention: "Exporter ses données (RGPD)", attendu: "La section export est disponible" },
  'G05-rediger': { intention: "Rédiger un document assisté", attendu: "Un brouillon sourcé est généré" },
  // ── H. Backoffice admin ──
  'H01-admin-balayage': { intention: "Parcourir tous les onglets du backoffice", attendu: "Chaque onglet se charge sans erreur" },
  'H02-admin-utilisateurs': { intention: "Consulter la liste des utilisateurs", attendu: "Les comptes sont listés" },
  'H03-admin-sante': { intention: "Consulter la santé du système", attendu: "L'onglet santé se charge" },
  'H04-admin-audit': { intention: "Consulter le journal d'audit", attendu: "L'onglet audit se charge" },
  // ── V2. Permissions & CRUD ──
  'W2-01-admin-refus-pro': { intention: "Un pro (non-admin) ouvre /admin", attendu: "Accès refusé (pas les droits admin)" },
  'W2-02-admin-refus-anonyme': { intention: "Un anonyme ouvre /admin", attendu: "Renvoyé au mur d'authentification (site privé)" },
  'W2-03-vault-refus-anonyme': { intention: "Un anonyme ouvre /vault", attendu: "Renvoyé au mur d'authentification (site privé)" },
  'W2-04-cabinet-member-sans-gestion': { intention: "Un membre simple ouvre le cabinet", attendu: "Il peut quitter mais pas supprimer/gérer" },
  'W2-05-cabinet-owner-gestion': { intention: "L'owner ouvre le cabinet", attendu: "Il peut supprimer le cabinet" },
  'W2-06-workspace-crud': { intention: "Créer puis supprimer un cabinet", attendu: "Le cabinet apparaît puis disparaît" },
  'W2-07-membre-invite-role-retrait': { intention: "Inviter un membre, changer son rôle, le retirer", attendu: "Le membre est ajouté puis retiré" },
  'W2-08-alerte-crud': { intention: "Créer puis supprimer une alerte", attendu: "L'alerte apparaît puis est supprimée" },
  'W2-09-cle-api-crud': { intention: "Créer puis révoquer une clé d'API", attendu: "La clé apparaît puis est révoquée" },
  'W2-10-prompt-crud': { intention: "Créer puis supprimer un prompt", attendu: "Le prompt apparaît puis est supprimé" },
  'W2-11-inscription-mdp-court': { intention: "S'inscrire avec un mot de passe trop court", attendu: "Inscription refusée" },
  'W2-12-changer-mdp-mauvais-ancien': { intention: "Changer le mot de passe avec un mauvais ancien", attendu: "Échec sans crash, volet compte maintenu" },
  // ── V3. Vault complet ──
  'W3-01-vault-citations': { intention: "Vérifier les citations d'un document", attendu: "Un décompte de références vérifiées s'affiche" },
  'W3-02-vault-extraire': { intention: "Extraire les métadonnées d'un document", attendu: "La matière est affichée" },
  'W3-03-vault-contre-argumentaire': { intention: "Générer un contre-argumentaire", attendu: "Un contre-argumentaire est produit" },
  'W3-04-vault-chronologie': { intention: "Extraire la chronologie d'un document", attendu: "Le panneau chronologie répond" },
  'W3-05-vault-hybride': { intention: "Interroger docs privés + corpus public", attendu: "Une réponse hybride est produite" },
  'W3-06-vault-comparer': { intention: "Comparer plusieurs documents", attendu: "Le tableau de comparaison s'affiche" },
  'W3-07-vault-playbook-creer': { intention: "Créer un playbook de revue", attendu: "Le playbook apparaît" },
  'W3-08-vault-revue-contrat': { intention: "Revoir un contrat contre un playbook", attendu: "Un verdict par règle s'affiche" },
  // ── V4. Recherche & insight ──
  'W4-01-filtre-type': { intention: "Filtrer par type jurisprudence", attendu: "Réponse avec parcours guidé" },
  'W4-02-filtre-annee': { intention: "Filtrer par années", attendu: "Réponse avec parcours guidé" },
  'W4-03-filtre-juridiction': { intention: "Filtrer par juridiction", attendu: "Réponse avec parcours guidé" },
  'W4-04-refus-avec-filtre-elargir': { intention: "Refus avec des filtres actifs", attendu: "Bouton « Élargir » proposé" },
  'W4-05-sauver-dans-dossier': { intention: "Ranger une réponse dans un dossier", attendu: "La fenêtre de rangement s'ouvre" },
  'W4-06-historique-detail': { intention: "Consulter son historique", attendu: "Une question passée est visible" },
  'W4-07-insight-profil-avocat': { intention: "Ouvrir la fiche d'un avocat", attendu: "La fiche (décisions) s'affiche" },
  'W4-08-insight-analytics-matiere': { intention: "Voir les analytics par matière", attendu: "Une matière est affichée" },
  // ── V5. Multi-acteurs ──
  'W5-01-nouveau-client-bout-en-bout': { intention: "Nouveau client : s'inscrire, poser, noter, partager", attendu: "Parcours complet réussi (lien copié)" },
  'W5-02-collaboration-cabinet': { intention: "Owner invite un membre qui rejoint depuis sa session", attendu: "Le membre voit le cabinet partagé" },
  'W5-03-cloison-bout-en-bout': { intention: "Owner restreint un dossier et n'autorise qu'un membre", attendu: "Le non-autorisé ne voit pas, l'autorisé voit" },
  // ── V6. Sous-actions admin ──
  'W6-01-admin-changer-plan': { intention: "Changer le plan d'un utilisateur", attendu: "Le plan est appliqué" },
  'W6-02-admin-toggle-admin': { intention: "Basculer le statut admin d'un utilisateur", attendu: "Le statut est basculé" },
  'W6-03-admin-inspecteur-probe': { intention: "Inspecter le retrieval d'une requête", attendu: "Des extraits sont remontés" },
  'W6-04-admin-banc-eval': { intention: "Lancer le banc d'évaluation", attendu: "Le rapport d'éval s'affiche" },
  'W6-05-admin-config-patch': { intention: "Modifier un réglage runtime", attendu: "Le réglage est appliqué" },
  'W6-06-admin-supprimer-user': { intention: "Supprimer un compte", attendu: "Le compte disparaît de la liste" },
  // ── V7. Destructifs & erreurs ──
  'W7-01-supprimer-dossier': { intention: "Supprimer un dossier", attendu: "Le dossier disparaît" },
  'W7-02-quitter-cabinet': { intention: "Un membre quitte un cabinet", attendu: "Le cabinet disparaît de sa liste" },
  'W7-03-revoquer-acces': { intention: "Révoquer l'accès à un dossier restreint", attendu: "L'associé ne voit plus le dossier" },
  'W7-04-upload-trop-gros-413': { intention: "Déposer un fichier trop volumineux", attendu: "Dépôt rejeté avec erreur" },
  // ── V8. Insight & admin avancés ──
  'W8-01-insight-comparer': { intention: "Comparer deux avocats", attendu: "La vue de comparaison s'affiche" },
  'W8-02-insight-filtre-matiere': { intention: "Filtrer les avocats par matière", attendu: "Un avocat de la matière reste listé" },
  'W8-03-admin-questions': { intention: "Consulter les questions loguées", attendu: "Une question seedée est visible" },
  'W8-04-admin-retours': { intention: "Consulter les retours utilisateurs", attendu: "L'onglet retours se charge" },
  'W8-05-admin-corpus': { intention: "Consulter l'état du corpus", attendu: "Le corpus indexé est affiché" },
  'W8-06-admin-activite': { intention: "Consulter l'activité par jour", attendu: "Le graphe d'activité s'affiche" },
  'W8-07-admin-routage-llm': { intention: "Consulter le routage LLM par sensibilité", attendu: "Le routage LLM est affiché" },
  'W8-08-corpus-info-menu': { intention: "Consulter la volumétrie du corpus", attendu: "Le nombre de décisions est affiché" },
  // ── V9. Variantes & compléments ──
  'W9-01-anonyme-mur': { intention: "Un anonyme ouvre le site", attendu: "Le mur d'authentification bloque tout accès" },
  'W9-02-vault-supprimer-doc': { intention: "Supprimer un document du Vault", attendu: "Le document disparaît" },
  'W9-03-alerte-verifier': { intention: "Vérifier une alerte", attendu: "L'alerte s'ouvre (check + résultats)" },
  'W9-04-alerte-verifier-toutes': { intention: "Vérifier toutes les alertes", attendu: "La vérification globale se déclenche" },
  'W9-05-permalien-contenu': { intention: "Ouvrir un permalien partagé", attendu: "Le contenu « réponse partagée » s'affiche" },
  'W9-06-changer-mdp-succes': { intention: "Changer son mot de passe avec succès", attendu: "Confirmation « mot de passe modifié »" },
  // ── V10. Erreurs atteignables & variantes ──
  'W10-01-inscription-email-existant': { intention: "S'inscrire avec un e-mail déjà pris", attendu: "Inscription refusée" },
  'W10-02-connexion-email-inconnu': { intention: "Se connecter avec un e-mail inconnu", attendu: "Connexion refusée" },
  'W10-03-inviter-non-inscrit': { intention: "Inviter un e-mail non inscrit", attendu: "Invitation rejetée (non ajouté)" },
  'W10-04-autoriser-non-membre': { intention: "Autoriser un non-membre sur un dossier", attendu: "Autorisation rejetée" },
  'W10-05-vault-vide': { intention: "Un nouveau compte ouvre son Vault", attendu: "Message « aucun document »" },
  'W10-06-insight-sans-resultat': { intention: "Rechercher un avocat inexistant", attendu: "0 résultat" },
  'W10-07-insight-tri-recent': { intention: "Trier les avocats par activité récente", attendu: "Tri « activité récente » appliqué" },
  'W10-08-insight-tri-taux': { intention: "Trier par taux estimé favorable", attendu: "Tri « taux estimé favorable » appliqué" },
  'W10-09-filtre-source-loi': { intention: "Filtrer par source « loi »", attendu: "Réponse avec parcours guidé" },
  'W10-10-filtres-combines': { intention: "Combiner type + années + juridiction", attendu: "Réponse avec parcours guidé" },
  // ── V11. Variantes recherche ──
  'W11-01-exemple-preset': { intention: "Cliquer une question d'exemple", attendu: "Réponse avec parcours guidé" },
  'W11-02-conversation-multitours': { intention: "Enchaîner deux questions", attendu: "Deux tours de conversation enregistrés" },
  'W11-03-nouvelle-recherche-reset': { intention: "Démarrer une nouvelle recherche", attendu: "Le fil est réinitialisé" },
  'W11-04-filtre-projet-loi': { intention: "Filtrer par projets de loi", attendu: "Réponse avec parcours guidé" },
  'W11-05-feedback-pouce-bas-champ': { intention: "Donner un pouce négatif", attendu: "Le champ « ce qui manquait » apparaît" },
  'W11-06-mentions-legales': { intention: "Consulter les mentions légales", attendu: "Le contenu légal s'affiche" },
  // ── V12. Vault profond ──
  'W12-01-chronologie-datee': { intention: "Chronologie d'un document daté", attendu: "Des dates apparaissent dans la chronologie" },
  'W12-02-supprimer-playbook': { intention: "Supprimer un playbook", attendu: "Le playbook disparaît" },
  'W12-03-comparer-3-docs': { intention: "Comparer trois documents", attendu: "Le tableau de comparaison s'affiche" },
  'W12-04-vault-ask-hybride-suite': { intention: "Question hybride docs + corpus", attendu: "Une réponse hybride est produite" },
  // ── V13. Insight profond ──
  'W13-01-profil-issue-estimee': { intention: "Voir l'issue estimée d'un avocat", attendu: "La section « issue estimée » s'affiche" },
  'W13-02-profil-confreres': { intention: "Voir les confrères récurrents", attendu: "La section « confrères » s'affiche" },
  'W13-03-profil-annees': { intention: "Voir l'activité par année", attendu: "La section « activité par année » s'affiche" },
  'W13-04-profil-juridiction': { intention: "Voir la répartition par juridiction", attendu: "La section « répartition par juridiction » s'affiche" },
  'W13-05-analytics-taux': { intention: "Voir le taux de succès estimé", attendu: "La colonne « taux » s'affiche" },
  // ── V14. Admin profond ──
  'W14-01-audit-entrees': { intention: "Vérifier la présence d'entrées d'audit", attendu: "Des entrées horodatées existent" },
  'W14-02-audit-filtre': { intention: "Filtrer le journal d'audit", attendu: "Le filtre s'applique sans erreur" },
  'W14-03-eval-detail': { intention: "Lire le détail du rapport d'éval", attendu: "L'en-tête du rapport s'affiche" },
  'W14-04-questions-2e': { intention: "Retrouver une 2ᵉ question loguée", attendu: "La question est visible" },
  'W14-05-probe-topk': { intention: "Inspecter le retrieval avec un topK", attendu: "Des extraits sont remontés" },
  // ── V15. Cabinet profond ──
  'W15-01-ranger-dans-dossier-existant': { intention: "Ranger une réponse dans un dossier existant", attendu: "Confirmation « rangée dans le dossier »" },
  'W15-02-ranger-dans-nouveau-dossier': { intention: "Ranger une réponse dans un nouveau dossier", attendu: "Confirmation « rangée dans le dossier »" },
  'W15-03-membre-sans-restreindre': { intention: "Un membre regarde les dossiers", attendu: "Il ne voit pas les contrôles de cloison" },
  // ── V16. Insight profond ──
  'W16-01-liste-et-recherche': { intention: "Chercher un avocat par son nom", attendu: "La liste se filtre sur le nom cherché" },
  'W16-02-tri-taux-estime': { intention: "Classer les avocats par taux de succès estimé", attendu: "Seuls les avocats à ≥10 issues estimables apparaissent" },
  'W16-03-filtre-matiere-et-vide': { intention: "Filtrer par matière puis chercher un inconnu", attendu: "Le domaine filtre la liste ; état vide propre" },
  'W16-04-profil-complet': { intention: "Lire une fiche avocat complète", attendu: "Cabinet, issue estimée, montants, positions, activité, juridictions, PDF" },
  'W16-05-confrere-adversaire': { intention: "Naviguer vers un adversaire récurrent puis revenir", attendu: "Profil du confrère ouvert, fil d'Ariane navigable" },
  'W16-06-parcours-matiere': { intention: "Explorer une matière depuis un profil et rebondir", attendu: "Tendances de la matière + position de l'avocat + rebond confrère" },
  'W16-07-comparateur': { intention: "Comparer deux avocats côte à côte", attendu: "Table de comparaison à 2 colonnes puis retour au profil" },
  'W16-08-export-csv-profil': { intention: "Exporter les décisions d'un avocat en tableur", attendu: "Un fichier CSV nommé d'après l'avocat est téléchargé" },
  'W16-09-cabinets-liste-et-fiche': { intention: "Étudier un cabinet et ses avocats", attendu: "Fiche cabinet (KPIs + avocats) puis bascule sur un profil" },
  'W16-10-cabinets-recherche-vide': { intention: "Chercher un cabinet inexistant", attendu: "État vide propre « Aucun cabinet »" },
  'W16-11-analytics-complet': { intention: "Lire le tableau de bord contentieux complet", attendu: "KPIs (dont montant/délai médians), 3 répartitions, articles visés" },
  'W16-12-methodo-rgpd': { intention: "Comprendre la méthodologie et exercer un droit RGPD", attendu: "Bloc jurimétrie visible et demande d'opposition enregistrée" },
  'W16-13-question-nominative-court-circuit': { intention: "Poser une question nominative sur un avocat", attendu: "Le profil court-circuite le RAG (profil + décisions)" },
  'W16-14-profil-en-echec-message': { intention: "Cliquer un avocat quand l'API profil est en panne", attendu: "Un message d'erreur visible (jamais d'échec silencieux)" },
  'W16-15-cabinet-en-echec-message': { intention: "Ouvrir une fiche cabinet quand l'API est en panne", attendu: "Un message d'erreur visible (jamais d'échec silencieux)" },
  'W17-01-deconnexion-desktop': { intention: "Se déconnecter depuis un écran d'ordinateur", attendu: "Bouton visible dans la barre latérale sans ouvrir de menu ; retour au mur de connexion" },
  // ── V18. Rédaction v2 ──
  'W18-01-generer-depuis-modele': { intention: "Générer une mise en demeure depuis un modèle avec variables et ton", attendu: "Document au squelette du modèle, fondements cités" },
  'W18-02-raffiner-et-versions': { intention: "Raffiner un document par instruction", attendu: "Contenu révisé et historique à 2 versions" },
  'W18-03-brouillon-persistant-reouverture': { intention: "Renommer, fermer puis rouvrir un brouillon", attendu: "Le brouillon renommé se rouvre avec son contenu" },
  'W18-04-restaurer-version': { intention: "Restaurer une version antérieure", attendu: "La restauration crée une 3e version (rien n'est perdu)" },
  'W18-05-enregistrer-comme-modele': { intention: "Capitaliser un document en modèle personnel", attendu: "Le modèle apparaît dans le sélecteur puis se supprime" },
  'W18-06-modele-cabinet-partage': { intention: "Partager un modèle au cabinet", attendu: "Un associé du cabinet voit le modèle partagé" },
  'W18-07-refus-gracieux': { intention: "Demander un document hors droit luxembourgeois", attendu: "Refus gracieux, aucun brouillon créé" },
  'W18-08-suppression-brouillon': { intention: "Supprimer un brouillon", attendu: "Retour à l'état vide de l'atelier" },
  'W18-09-exemples-et-route': { intention: "Découvrir la rédaction par son URL et un exemple", attendu: "Vue pleine page, exemple qui pré-remplit le formulaire, document généré" },
  // ── W19. Carte thématique sur TOUTES les réponses (y compris de suivi) ──
  'W19-01-carte-sur-reponse-suivi': { intention: "Approfondir via une question de suivi", attendu: "La réponse de suivi est aussi présentée en carte thématique, pas en texte brut" },
  // ── W20. Ergonomie unifiée (LOT 1) ──
  'W20-01-zones-navigation': { intention: "Se repérer dans la navigation", attendu: "La barre latérale est organisée par zones d'intention (Travailler/Décider/Suivre)" },
  'W20-02-compte-unifie': { intention: "Gérer son compte", attendu: "Un seul menu (avatar) rassemble profil, mot de passe et déconnexion" },
  'W20-03-nav-parite-desktop-mobile': { intention: "Retrouver une action sur desktop ET mobile", attendu: "La même navigation alimente la barre latérale et le tiroir" },
  'W20-04-admin-sans-double-login': { intention: "Accéder au backoffice", attendu: "L'admin s'ouvre en réutilisant la session, sans second login" },
  // ── W21. Palette ⌘K — recherche fédérée (LOT 2) ──
  'W21-01-cmdk-raccourci': { intention: "Ouvrir la recherche rapide au clavier", attendu: "⌘K ouvre la palette, Échap la ferme" },
  'W21-02-cmdk-champ-lateral': { intention: "Ouvrir la recherche rapide à la souris", attendu: "Le champ « Rechercher… » de la barre latérale ouvre la palette" },
  'W21-03-cmdk-question': { intention: "Poser une question depuis la palette", attendu: "Entrée lance la recherche juridique dans la vue principale" },
  'W21-04-cmdk-avocat': { intention: "Trouver un avocat depuis la palette", attendu: "Le résultat avocat ouvre directement son profil Insight" },
  'W21-05-cmdk-prefixe-cabinet': { intention: "Trouver un cabinet via le préfixe c:", attendu: "Le résultat cabinet ouvre directement sa fiche" },
  // ── W22. Accueil « Aujourd'hui » (LOT 3) ──
  'W22-01-accueil-tableau-de-bord': { intention: "Prendre ses repères en arrivant", attendu: "L'accueil affiche un tableau de bord (salutation, volumétrie, veille, reprise)" },
  'W22-02-reprendre-depuis-accueil': { intention: "Reprendre une recherche récente", attendu: "L'accueil propose l'historique, un clic pré-remplit le champ" },
  // ── W23. Papier à en-tête (logo, signature, visionneuse) ──
  'W23-01-logo-demande-puis-fourni': { intention: "Habiller mes documents du logo du cabinet", attendu: "Le logo est demandé s'il manque ; une fois fourni, l'en-tête (logo + cabinet + date) habille le document" },
  'W23-02-signature-et-visionneuse': { intention: "Signer et prévisualiser le document final", attendu: "La signature chargée s'affiche ; l'aperçu montre la feuille finale (en-tête + texte + signature)" },
  'W23-03-en-tete-persistant': { intention: "Retrouver mon papier à en-tête au prochain document", attendu: "L'en-tête habille d'office les nouveaux documents, logo et signature restent remplaçables" },
  // ── W24. Thème sombre + export Word ──
  'W24-01-theme-sombre-persistant': { intention: "Travailler en thème sombre", attendu: "La bascule du menu de compte passe l'app en sombre, persiste au rechargement, et revient au clair" },
  'W24-02-export-word': { intention: "Ouvrir mon document dans Word", attendu: "« Word » télécharge un .doc au nom du brouillon (papier à en-tête inclus)" },
  // ── W25. Chaîne de travail Vault (B11 v1) ──
  'W25-01-chaine-complete': { intention: "Analyser un document en un geste", attendu: "La chaîne exécute citations → contre-argumentaire → résumé et empile les 3 résultats" },
  // ── W26. Veille v2 : auto-vérification (I1), recettes (I2), approfondie (I3) ──
  'W26-01-contre-argumentaire-verifie': { intention: "Faire confiance à une sortie LLM", attendu: "Le contre-argumentaire porte le badge « n/n citations vérifiées au corpus »" },
  'W26-02-recette-question': { intention: "Lancer un travail type en un clic", attendu: "La recette « question » de l'accueil lance la recherche et aboutit" },
  'W26-03-recette-redaction-preremplie': { intention: "Démarrer un courrier type en un clic", attendu: "La recette « rédaction » ouvre l'atelier pré-rempli (modèle + instruction)" },
  'W26-04-recherche-approfondie': { intention: "Creuser une question complexe", attendu: "« Approfondie » produit un mémo multi-axes structuré et sourcé" },
};
